name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
  workflow_dispatch:

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    environment: actions # Environment Secrets are scoped inside of the "actions" environment.
    steps:
    - uses: actions/checkout@master
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@2.1.1
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: wpgraphql-ide

